spring:
  application:
    name: online-library-spring-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=online_library_schema
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#  doc:
#    api-docs:
#      path: /v3/api-docs
#    swagger-ui:
#      path: /swagger-ui.html
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#  main:
#    web-application-type: none
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

server:
  port: 8080

authentication:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06HYOGZGR/pSrFv2Sulzxk+QX8mrEauCGO5BE/0lwgMrwsxx0jP8fcwm6lRpvGIplHnj8Zy4VUxhXsXJoB54dxMGsc2AJFornNX5GHAcD4FEq4Q2tgtZXSnEA2kq2zi4mlmgXHCLKqSfkrVTGKrWh5FMYtw5vVEULaak4VMc6MypQ/MT6gzXsFspTc+AEBwCo4t6qtwkDWCoLEB0W5R6CkGqCpO+xl6vN4lV6+GF12xHOdv2z2e459z9JTzjjnxz0lvdeXfS/jAu8MsAw7hOS4LDS7pa4N+UGCUUYusUPWMTnNdkniknlcx++hQm8gnJJ7SR8IuZnZ5hlMMHxyHYnwIDAQAB
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTodg4ZkZH+lKsW/ZK6XPGT5BfyasRq4IY7kET/SXCAyvCzHHSM/x9zCbqVGm8YimUeePxnLhVTGFexcmgHnh3EwaxzYAkWiuc1fkYcBwPgUSrhDa2C1ldKcQDaSrbOLiaWaBccIsqpJ+StVMYqtaHkUxi3Dm9URQtpqThUxzozKlD8xPqDNewWylNz4AQHAKji3qq3CQNYKgsQHRblHoKQaoKk77GXq83iVXr4YXXbEc52/bPZ7jn3P0lPOOOfHPSW915d9L+MC7wywDDuE5LgsNLulrg35QYJRRi6xQ9YxOc12SeKSeVzH76FCbyCckntJHwi5mdnmGUwwfHIdifAgMBAAECggEAVdV0ATf19FaCNnbb9zklJD774uXD1NhXXS4wxd8r87reglTyKxu7offtpqfS9L1peNdRDJsQJkRiz5Hvu1nwaPcWBYJAIT5TJvqf23oI338B74ChwgbrWT5Jykpav+wK70s/n45j20lGkTWqvLv5Y6WaMhR49KBQS02l3N+dP4uZZaMGZgcBFquG6FtkMsd1s2UCQtMywxIqrCFlSaYmdDbpw70GlTTTaxFjrBJON4hR/cUxcWoeOlx2ywWmu8gUC9VQTiaHBzIYcAG28lgXV6Bxf8CcpfwL/bfH/ASm3bA7oEkIh+zXuiLcwwqyqu52gCxZxTDWHvlyBpfBp/k3TQKBgQDdasIICgcddF3By5Wac7FE3awZj1fzspzPCrHiABtTplrwFpwr5HesOqPxkl+R8ehbitFHeosxdERkSanWob7Ze58IER8ksmOUnx5cQGG697Q6o+WseX+OXmGXtEygMY1mJ181v3DJK2dM+ygunRhRk1BvyJFivcoG2z/maPaj/QKBgQD0r9iPZHELwpVql35dMHmCxO+z3BOZqdePi+S6SZpxmdixrHBTXiZIOOKmTc5YD89dpKNq/2Yrv8CX+gJhA8U8uaVRYnGzZf/fb5AnezRPnRoGsP0pbQ45ufBtwECR/HF1OjZjzZP4qbvGdd8NfXl7twQ2e3RAiUJxYuWXehS7ywKBgQCmdJzcGFXTAel+SMP2cmVhRVkdehL/5VZXnE2wfq4Mi/Kvrf/IS6DgPNGFSapJeNhbAZhlqS29hw/naS2iasSkkXg0Q1LrbqTIVXsolUojmhbHQvHmYQzRBglOWECG6dnIY28DZCGxSs0FJYfGy1k98oa1Es6hsdaQowF+AYjyLQKBgQDcrhfPw5PdOmKN3xH9tDFzCnDxs0QOK8sZUN86UBW17T4tiEtKNTirnHp16Oh4LdIlL86fOrcIMAngR4CLxN3HlduO2g2X8h9igfjuUsTsJNGLRWceTJgu4g8AvQq/X4Foa9cQDiIte8+5/ybrwMWnGXn4NUG0ztaY8swE4PsAHwKBgAxI+NVK6B6l/a+kweHdhTfOGkryCLfQBm8m+cdyUpOPemcnTHBPCxRozUBuIAJjlSou2TaWnJbF66LUgorLZWZXOuP2hQt8esI7bZZKgungmyUQx4oboulvoqiDvD/mA7naLfaZPKd92VJObPqw9u8xd2kOssCY56KJdNfOqT/Z



    access:
      expiration-in-ms: 120000
    refresh:
      expiration-in-ms: 600000

